import type { PoderData } from '@/types/poder';

export const DEMO_PODER: PoderData = {
  poderdante: {
    nombre: 'MARJORIE KATHLEEN BRAATZ',
    nacionalidad: 'Canadian',
    estadoCivil: 'casado',
    ocupacion: 'Retired',
    domicilio: 'Paseo De Los Cocoteros 111, Int 404, Nuevo Vallarta, Bahía de Banderas, Nayarit, 63735',
    pasaporte: 'AC536054',
    fechaNacimiento: '29/03/1962',
    genero: 'F',
  },
  apoderados: [
    { nombre: 'ROLANDO ROMERO GARCÍA' },
    { nombre: 'CLAUDIA REBECA CASTILLO SOTO' },
  ],
  inmueble: {
    modo: 'fideicomiso',
    descripcionEN: "Apartment 404, type C-PH, located on the fourth level of the Nitta Nuevo Vallarta condominium, at Paseo de los Cocoteros Avenue number 111 North, Nuevo Vallarta nautical-tourist subdivision, Bahía de Banderas, Nayarit, Postal Code 63735. Covered area: 123.8003 sqm. Uncovered terrace area: 2.1410 sqm. Pergola area: 17.7273 sqm. Terrace and pool area: 60.7026 sqm. Total area: 204.3712 sqm. Undivided share: 2.293%. Consisting of: laundry area, distribution hallway, pergola area, terrace and pool area, air conditioning equipment area, kitchen, living-dining room, terrace, 1 bedroom with bathroom, walk-in closet and terrace, 1 bedroom with bathroom and terrace. Parking space 404. Storage unit 404.",
    descripcion: 'Departamento 404, tipo "C-PH", ubicado en cuarto nivel, del condominio Nitta Nuevo Vallarta, en avenida Paseo de los Cocoteros número 111 norte, Fraccionamiento náutico turístico Nuevo Vallarta, Bahía de Banderas, Nayarit, Código Postal 63735. Área cubierta: 123.8003 m². Área terraza descubierta: 2.1410 m². Área de pergolado: 17.7273 m². Área de terraza y alberca: 60.7026 m². Área total: 204.3712 m². % de indiviso: 2.293%. Consta de: área de lavandería, pasillo distribuidor, área de pergolado, área de terraza y alberca, área de equipo aire acondicionado, cocina, sala comedor, terraza, 1 recámara con baño, vestidor y terraza, 1 recámara con baño y terraza. Estacionamiento 404. Bodega 404.',
    fideicomisoNumero: '751699',
    bancoFiduciario: 'BANCO MERCANTIL DEL NORTE, SOCIEDAD ANÓNIMA, INSTITUCIÓN DE BANCA MÚLTIPLE, GRUPO FINANCIERO BANORTE, DIVISIÓN FIDUCIARIA',
    cuentaPredial: 'U016345',
    escrituraNumero: '',
    escrituraFecha: '',
    escrituraNotario: '',
    escrituraNotaria: '',
    escrituraVolumen: '',
    escrituraFolio: '',
    rppEstado: 'nayarit',
    rppTipo: 'folio_real',
    rppFolioReal: '',
    rppLibroNay: '',
    rppSeccionNay: '',
    rppSerieNay: '',
    rppPartidaNay: '',
    rppDocumentoJal: '',
    rppFoliosJal: '',
    rppLibroJal: '',
    rppSeccionJal: '',
    departamento: 'Departamento 404, tipo C-PH',
    nombreCondominio: 'Nitta Nuevo Vallarta',
    direccion: 'Av. Paseo de los Cocoteros 111 Norte',
    municipio: 'Bahía de Banderas',
    estado: 'Nayarit',
    cp: '63735',
  },
  tipos: ['pleitos_cobranzas', 'administracion', 'dominio'],
  facultades: {
    adquirirDerechos: true,
    darInstrucciones: true,
    enajenar: true,
    cederDerechos: true,
    donaciones: false,
    conveniosModificatorios: true,
    ejecucionAmpliaFideicomiso: true,
    ratificarInstrumentoPublico: true,
    otorgarFiniquito: true,
    firmarDocumentos: true,
    escrow: true,
    isr: true,
  },
  lugar: '',
  fecha: '',
};
